// <auto-generated />
using System;
using Finlyze.Migrations.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finlyze.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250716191626_InitialDeploy")]
    partial class InitialDeploy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Finlyze.Domain.Entity.FinancialTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserAccountId");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.ToTable("FinancialTransaction", (string)null);
                });

            modelBuilder.Entity("Finlyze.Domain.Entity.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("SystemLog", (string)null);
                });

            modelBuilder.Entity("Finlyze.Domain.Entity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserAccount", (string)null);
                });

            modelBuilder.Entity("Finlyze.Domain.Entity.FinancialTransaction", b =>
                {
                    b.HasOne("Finlyze.Domain.Entity.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Finlyze.Domain.ValueObject.TransactionObjects.Amount", "Amount", b1 =>
                        {
                            b1.Property<int>("FinancialTransactionId")
                                .HasColumnType("Int");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.HasKey("FinancialTransactionId");

                            b1.ToTable("FinancialTransaction");

                            b1.WithOwner()
                                .HasForeignKey("FinancialTransactionId");
                        });

                    b.OwnsOne("Finlyze.Domain.ValueObject.TransactionObjects.CreateAt", "CreateAt", b1 =>
                        {
                            b1.Property<int>("FinancialTransactionId")
                                .HasColumnType("Int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("DateTime")
                                .HasColumnName("CreateAt");

                            b1.HasKey("FinancialTransactionId");

                            b1.ToTable("FinancialTransaction");

                            b1.WithOwner()
                                .HasForeignKey("FinancialTransactionId");
                        });

                    b.OwnsOne("Finlyze.Domain.ValueObject.TransactionObjects.Description", "Description", b1 =>
                        {
                            b1.Property<int>("FinancialTransactionId")
                                .HasColumnType("Int");

                            b1.Property<string>("Value")
                                .HasColumnType("Nvarchar(300)")
                                .HasColumnName("Description");

                            b1.HasKey("FinancialTransactionId");

                            b1.ToTable("FinancialTransaction");

                            b1.WithOwner()
                                .HasForeignKey("FinancialTransactionId");
                        });

                    b.OwnsOne("Finlyze.Domain.ValueObject.TransactionObjects.Title", "Title", b1 =>
                        {
                            b1.Property<int>("FinancialTransactionId")
                                .HasColumnType("Int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("Nvarchar(100)")
                                .HasColumnName("Title");

                            b1.HasKey("FinancialTransactionId");

                            b1.ToTable("FinancialTransaction");

                            b1.WithOwner()
                                .HasForeignKey("FinancialTransactionId");
                        });

                    b.OwnsOne("Finlyze.Domain.ValueObject.TransactionObjects.TranType", "TranType", b1 =>
                        {
                            b1.Property<int>("FinancialTransactionId")
                                .HasColumnType("Int");

                            b1.Property<int>("Value")
                                .HasColumnType("Int")
                                .HasColumnName("TranType");

                            b1.HasKey("FinancialTransactionId");

                            b1.ToTable("FinancialTransaction");

                            b1.WithOwner()
                                .HasForeignKey("FinancialTransactionId");
                        });

                    b.OwnsOne("Finlyze.Domain.ValueObject.TransactionObjects.UpdateAt", "UpdateAt", b1 =>
                        {
                            b1.Property<int>("FinancialTransactionId")
                                .HasColumnType("Int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("DateTime")
                                .HasColumnName("UpdateAt");

                            b1.HasKey("FinancialTransactionId");

                            b1.ToTable("FinancialTransaction");

                            b1.WithOwner()
                                .HasForeignKey("FinancialTransactionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("CreateAt")
                        .IsRequired();

                    b.Navigation("Description");

                    b.Navigation("Title")
                        .IsRequired();

                    b.Navigation("TranType")
                        .IsRequired();

                    b.Navigation("UpdateAt")
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Finlyze.Domain.Entity.SystemLog", b =>
                {
                    b.OwnsOne("Finlyze.Domain.ValueObject.AppLogObjects.CreateAt", "CreateAt", b1 =>
                        {
                            b1.Property<int>("SystemLogId")
                                .HasColumnType("Int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("DateTime")
                                .HasColumnName("CreateAt");

                            b1.HasKey("SystemLogId");

                            b1.ToTable("SystemLog");

                            b1.WithOwner()
                                .HasForeignKey("SystemLogId");
                        });

                    b.OwnsOne("Finlyze.Domain.ValueObject.AppLogObjects.Description", "Description", b1 =>
                        {
                            b1.Property<int>("SystemLogId")
                                .HasColumnType("Int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("Nvarchar(200)")
                                .HasColumnName("Description");

                            b1.HasKey("SystemLogId");

                            b1.ToTable("SystemLog");

                            b1.WithOwner()
                                .HasForeignKey("SystemLogId");
                        });

                    b.OwnsOne("Finlyze.Domain.ValueObject.AppLogObjects.LogType", "LogType", b1 =>
                        {
                            b1.Property<int>("SystemLogId")
                                .HasColumnType("Int");

                            b1.Property<int>("Value")
                                .HasColumnType("Int")
                                .HasColumnName("LogType");

                            b1.HasKey("SystemLogId");

                            b1.ToTable("SystemLog");

                            b1.WithOwner()
                                .HasForeignKey("SystemLogId");
                        });

                    b.OwnsOne("Finlyze.Domain.ValueObject.AppLogObjects.Title", "Title", b1 =>
                        {
                            b1.Property<int>("SystemLogId")
                                .HasColumnType("Int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("Nvarchar(100)")
                                .HasColumnName("Title");

                            b1.HasKey("SystemLogId");

                            b1.ToTable("SystemLog");

                            b1.WithOwner()
                                .HasForeignKey("SystemLogId");
                        });

                    b.Navigation("CreateAt")
                        .IsRequired();

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("LogType")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Finlyze.Domain.Entity.UserAccount", b =>
                {
                    b.OwnsOne("Finlyze.Domain.ValueObject.UserAccountObject.Active", "Active", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("Value")
                                .HasColumnType("Bit")
                                .HasColumnName("Active");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccount");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("Finlyze.Domain.ValueObject.UserAccountObject.BirthDate", "BirthDate", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("Value")
                                .HasColumnType("Date")
                                .HasColumnName("BirthDate");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccount");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("Finlyze.Domain.ValueObject.UserAccountObject.CreateAt", "CreateAt", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("DateTime")
                                .HasColumnName("CreateAt");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccount");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("Finlyze.Domain.ValueObject.UserAccountObject.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("Nvarchar(254)")
                                .HasColumnName("Email");

                            b1.HasKey("UserAccountId");

                            b1.HasIndex(new[] { "Value" }, "Unique_Key_Email_UserAccount")
                                .IsUnique();

                            b1.ToTable("UserAccount");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("Finlyze.Domain.ValueObject.UserAccountObject.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("Nvarchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccount");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("Finlyze.Domain.ValueObject.UserAccountObject.Password", "Password", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("Nvarchar(255)")
                                .HasColumnName("Password");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccount");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("Finlyze.Domain.ValueObject.UserAccountObject.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("Nvarchar(20)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("UserAccountId");

                            b1.HasIndex(new[] { "Value" }, "Unique_Key_PhoneNumber_UserAccount")
                                .IsUnique();

                            b1.ToTable("UserAccount");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.OwnsOne("Finlyze.Domain.ValueObject.UserAccountObject.Role", "Role", b1 =>
                        {
                            b1.Property<Guid>("UserAccountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Value")
                                .HasColumnType("Int")
                                .HasColumnName("Role");

                            b1.HasKey("UserAccountId");

                            b1.ToTable("UserAccount");

                            b1.WithOwner()
                                .HasForeignKey("UserAccountId");
                        });

                    b.Navigation("Active")
                        .IsRequired();

                    b.Navigation("BirthDate")
                        .IsRequired();

                    b.Navigation("CreateAt")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("PhoneNumber")
                        .IsRequired();

                    b.Navigation("Role")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
